projectName: iow-allegemein
dockerImageName: kartoza/geoserver
memory: 2048
applicationName: iow-geoserver
rulePriority: 97
containerPort: 8080
healthCheck: /api/geoserver/web/
condition: /api/geoserver/*
contextPath: /api/geoserver/*
gitRepoUrl: https://github.com/usgs/iow-geoserver.git
gitRepoCredentialsId: GITHUB_ACCESS_TOKEN
healthCheckTimeoutSeconds: 45
healthCheckIntervalSeconds: 60
listenerPort: 443
envVars:
  - name: GEOSERVER_DATA_DIR
    value: /data
mounts:
  - name: GEOSERVER_DATA_DIR_MOUNT
    source: /efs
    destination: /data
    readOnly: False
# configuration repository paths
configRepoPath: "wma/docker/iow/iow-geoserver"
configCredentialsId: "wma-eto-eb-rsa"
