projectName: iow-allgemein
dockerImageName: kartoza/geoserver
memory: 2048
applicationName: iow-geoserver
launchType: EC2
containerPort: 8080
healthCheck: /geoserver/web/
gitRepoUrl: https://github.com/usgs/iow-geoserver.git
gitRepoCredentialsId: GITHUB_ACCESS_TOKEN
healthCheckTimeoutSeconds: 45
healthCheckIntervalSeconds: 60
listenerPort: 443
envVars:
  - name: GEOSERVER_DATA_DIR
    value: /data
mounts:
  - name: GEOSERVER_DATA_DIR_MOUNT
    source: /efs
    destination: /data
    readOnly: False
# configuration repository paths
configRepoPath: "wma/docker/iow/iow-geoserver"
configCredentialsId: "wma-eto-eb-rsa"
urlRules:
  - type: forward
    conditions:
      - "/geoserver/*"
    priority: 97
