projectName: iow-allgemein
dockerImageName: kartoza/geoserver
memory: 3072
cpu: 1024
applicationName: iow-geoserver
containerPort: 8080
healthCheck: /geoserver/web/
gitRepoUrl: https://github.com/usgs/iow-geoserver.git
gitRepoCredentialsId: GITHUB_ACCESS_TOKEN
healthCheckTimeoutSeconds: 45
healthCheckIntervalSeconds: 60
listenerPort: 443
# configuration repository paths
configRepoPath: "wma/docker/iow/iow-geoserver"
configCredentialsId: "wma-eto-eb-rsa"
urlRules:
  - type: forward
    conditions:
      - "/geoserver/*"
    priority: 97
